//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 11:41:40 AM GMT 
//


package com.vbsapi.org;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateGenerated" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VBLoadList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VB">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="VRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DateBooked" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TimeBooked" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Target" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="VBR" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateGenerated",
    "vbLoadList"
})
@XmlRootElement(name = "VBLoad")
public class VBLoad {

    @XmlElement(name = "DateGenerated", required = true)
    protected String dateGenerated;
    @XmlElement(name = "VBLoadList", required = true)
    protected VBLoad.VBLoadList vbLoadList;

    /**
     * Gets the value of the dateGenerated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateGenerated() {
        return dateGenerated;
    }

    /**
     * Sets the value of the dateGenerated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateGenerated(String value) {
        this.dateGenerated = value;
    }

    /**
     * Gets the value of the vbLoadList property.
     * 
     * @return
     *     possible object is
     *     {@link VBLoad.VBLoadList }
     *     
     */
    public VBLoad.VBLoadList getVBLoadList() {
        return vbLoadList;
    }

    /**
     * Sets the value of the vbLoadList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VBLoad.VBLoadList }
     *     
     */
    public void setVBLoadList(VBLoad.VBLoadList value) {
        this.vbLoadList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VB">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="VRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DateBooked" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TimeBooked" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Target" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="VBR" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vb"
    })
    public static class VBLoadList {

        @XmlElement(name = "VB", required = true)
        protected VBLoad.VBLoadList.VB vb;

        /**
         * Gets the value of the vb property.
         * 
         * @return
         *     possible object is
         *     {@link VBLoad.VBLoadList.VB }
         *     
         */
        public VBLoad.VBLoadList.VB getVB() {
            return vb;
        }

        /**
         * Sets the value of the vb property.
         * 
         * @param value
         *     allowed object is
         *     {@link VBLoad.VBLoadList.VB }
         *     
         */
        public void setVB(VBLoad.VBLoadList.VB value) {
            this.vb = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="VRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DateBooked" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TimeBooked" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Target" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="VBR" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vrn",
            "dateBooked",
            "timeBooked",
            "amount",
            "source",
            "target"
        })
        public static class VB {

            @XmlElement(name = "VRN", required = true)
            protected String vrn;
            @XmlElement(name = "DateBooked", required = true)
            protected String dateBooked;
            @XmlElement(name = "TimeBooked", required = true)
            protected String timeBooked;
            @XmlElement(name = "Amount")
            protected float amount;
            @XmlElement(name = "Source", required = true)
            protected String source;
            @XmlElement(name = "Target", required = true)
            protected String target;
            @XmlAttribute(name = "VBR")
            protected Byte vbr;

            /**
             * Gets the value of the vrn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVRN() {
                return vrn;
            }

            /**
             * Sets the value of the vrn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVRN(String value) {
                this.vrn = value;
            }

            /**
             * Gets the value of the dateBooked property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateBooked() {
                return dateBooked;
            }

            /**
             * Sets the value of the dateBooked property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateBooked(String value) {
                this.dateBooked = value;
            }

            /**
             * Gets the value of the timeBooked property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeBooked() {
                return timeBooked;
            }

            /**
             * Sets the value of the timeBooked property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeBooked(String value) {
                this.timeBooked = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             */
            public float getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             */
            public void setAmount(float value) {
                this.amount = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the target property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTarget() {
                return target;
            }

            /**
             * Sets the value of the target property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTarget(String value) {
                this.target = value;
            }

            /**
             * Gets the value of the vbr property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getVBR() {
                return vbr;
            }

            /**
             * Sets the value of the vbr property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setVBR(Byte value) {
                this.vbr = value;
            }

        }

    }

}
